imports:
    - { resource: admin/ }
easy_admin:
    list:
        title: '%%entity_label%%'
        actions:
            - { name: 'edit', label: '', title: 'Éditer', icon: 'pencil-alt' }
            - { name: 'delete', label: '', title: 'Supprimer', icon: 'trash' }
            - { name: 'new', label: 'Ajouter', title: '', icon: 'plus' }
    show:
        title: '%%entity_label%%'
    search:
        title: '%%entity_label%%'
    edit:
        title: '%%entity_label%%'
        actions:
            - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash' }
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    design:
        brand_color: '#A1BB0C'
        form_theme: 'back/easyadmin/bootstrap_3_layout.html.twig'
        assets:
            favicon: 'assets/img/favicon.ico'
            css:
                - 'assets/js/featherlight.min.css'
                - 'assets/css/select2-bootstrap.min.css'
                - 'assets/css/knacss.css'
                - 'assets/css/back.css'
                - 'assets/js/jstree/themes/style.css'
                - 'assets/js/fancybox/jquery.fancybox.min.css'
                - 'assets/js/jquery-ui.min.css'
            js:
                # dans base.html.twig - '../assets/js/jquery-3.2.1.min.js'
#                - 'assets/js/fancybox/jquery.fancybox.min.js'
                - 'assets/js/fontawesome-all.min.js'
                - 'assets/js/jscookie/cookie.js'
                - 'assets/js/jstree/jstree.min.js'
                - 'assets/js/jquery-ui.min.js'
                - 'assets/js/jsBack.js'
                - 'assets/js/jsHeaderSidebar.js'
        templates:
            layout: 'back/base.html.twig'
            menu: 'back/menu/menuPrincipal.html.twig'
            new: 'back/easyadmin/new.html.twig'
            list: 'back/easyadmin/list.html.twig'
            edit: 'back/easyadmin/edit.html.twig'
            field_toggle: 'back/easyadmin/fields/field_toggle.html.twig'
            field_association: 'back/easyadmin/fields/field_association.html.twig'
            field_text: 'back/easyadmin/fields/field_text.html.twig'
            field_image: 'back/easyadmin/fields/field_image.html.twig'
            paginator: 'back/easyadmin/paginator.html.twig'
            flash_messages: 'back/easyadmin/flash_messages.html.twig'
        menu:
            - { label: 'Tableau de bord', icon: 'tachometer-alt', route: 'tableauDeBord' }
            - label: 'Contenus'
              icon: 'puzzle-piece'
              children:
              - label: 'Pages'
                icon: ''
                children:
                  - { route: 'easyadmin', label: 'Ajouter une page', type: 'route', menu_index: 0, submenu_index: 0, icon: 'fa-plus-circle mrs', default: true, params: { action: 'new', entity: 'Page_Active' } }
                  - { entity: 'Page_Active', label: 'Toutes les pages', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
                  - { entity: 'Page_Corbeille', label: 'Pages à la corbeille', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
              - { label: 'Référencement', route: 'referencement' }
              - { entity: 'BlocPartage', label: 'Blocs partagés', icon: '' }
              - label: 'Commentaires'
                icon: ''
                children:
                  - { entity: 'Commentaire_Actif', label: 'Tous les commentaires', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
                  - { entity: 'Commentaire_Corbeille', label: 'Commentaires à la corbeille', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
              - label: 'Catégories'
                icon: ''
                children:
                  - { route: 'easyadmin', label: 'Ajouter une catégorie', type: 'route', menu_index: 0, submenu_index: 0, icon: 'fa-plus-circle mrs', default: true, params: { action: 'new', entity: 'Categorie' } }
                  - { entity: 'Categorie', label: 'Toutes les catégories', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
                  - { route: 'easyadmin', label: 'Ajouter un type de catégorie', type: 'route', menu_index: 0, submenu_index: 0, icon: 'fa-plus-circle mrs', default: true, params: { action: 'new', entity: 'TypeCategorie' } }
                  - { entity: 'TypeCategorie', label: 'Tous les types de catégories', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
              - label: 'Langues'
                icon: ''
                children:
                  - { entity: 'Langue', label: 'Toutes les langues', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
                  - { route: 'traductionsPages', label: 'Traduction des pages', type: 'route', menu_index: 0, submenu_index: 0, icon: '', default: true, css_class: 'traductions', params: { } }
                  - { route: 'traductionsTemplates', label: 'Traduction des templates', type: 'route', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
              - label: 'Interface'
                icon: ''
                children:
                  - { entity: 'Region', label: 'Régions', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
                  - { entity: 'Menu', label: 'Menus', type: 'entity', menu_index: 0, submenu_index: 0, icon: '', default: true, params: { } }
            - { label: 'Médiathèque', icon: 'images', route: 'mediatheque' }
            - { entity: 'Utilisateur', label: 'Comptes', icon: 'users', droit: 'comptes' }
            - label: 'Outils'
              icon: 'wrench'
              children:
                - { entity: 'Configuration', label: 'Configuration générale', icon: '', params: { action: 'edit', id: 1 }, droit: 'config' }
                - { label: 'Thèmes', icon: '', route: 'theme', droit: 'themes' }
                - { label: 'Blocs', icon: '', route: 'configurationBlocs', droit: 'configBlocs' }
                - { label: 'Sauvegardes', icon: '', route: 'sauvegarde', droit: 'sauvegardes' }
                - { label: 'Droits', icon: '', route: 'droits', droit: 'droits' }