imports:
    - { resource: admin/ }
easy_admin:
    list:
        title: '%%entity_label%%'
        actions:
            - { name: 'edit', label: '', title: 'Éditer', icon: 'pencil-alt' }
            - { name: 'delete', label: '', title: 'Supprimer', icon: 'trash' }
    show:
        title: '%%entity_label%%'
    search:
        title: '%%entity_label%%'
    edit:
        title: '%%entity_label%%'
        actions:
            - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash' }
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i'
    design:
        brand_color: '#A1BB0C'
        assets:
            favicon: '../assets/img/front/favicon.ico'
            css:
                - '../assets/css/back/knacss/knacss.css'
                - '../assets/css/back/headerAsideBack.css'
                - '../assets/css/back/contentBack.css'
                - '../assets/js/back/jstree/themes/style.css'
            js:
                # dans base.html.twig - '../assets/js/jquery-3.2.1.min.js'
                - '../assets/js/fontawesome-all.min.js'
                - '../assets/js/back/jsBack.js'
                - '../assets/js/back/jstree/jstree.min.js'
        templates:
            layout: 'back/base.html.twig'
            menu: 'back/menu/menuPrincipal.html.twig'
            list: 'back/easyadmin/list.html.twig'
            edit: 'back/easyadmin/edit.html.twig'
            field_toggle: 'back/easyadmin/field_toggle.html.twig'
        menu:
            - { entity: 'Utilisateur', label: 'Comptes', icon: 'users' }
            - { entity: 'Configuration', icon: 'cog', params: { action: 'edit', id: 1 } }
            - label: 'Outils'
              icon: 'wrench'
              children:
                - { entity: 'Champ', icon: '' }
                - { entity: 'TypeModule', icon: '' }
                - { label: 'Traductions', icon: '', url: '#' }
                - { label: 'Corbeille', icon: '', url: '#' }
                - { entity: 'Page_Corbeille', icon: '' }
                - { entity: 'Commentaire_Corbeille', icon: '' }
            - { label: 'Médiathèque', icon: 'folder', route: 'mediatheque' }
            - { label: 'Newsletter', icon: 'paper-plane', url: '#' }
            - label: 'Contenus'
              icon: 'puzzle-piece'
              children:
              - { entity: 'Page_Active', icon: '', default: true }
              - { entity: 'Commentaire_Actif', icon: '' }
              - { entity: 'TypeCategorie', icon: '' }
              - { entity: 'Categorie', icon: '' }
              - { entity: 'Langue', icon: '' }
              - { entity: 'Zone', icon: '' }
              - { entity: 'Menu', icon: '' }
            - { label: 'Voir le site', route: 'accueil', icon: 'home' }
