easy_admin:
    entities:
        Commentaire_Actif:
            class: App\Entity\Commentaire
            controller: App\Controller\Back\AdminController
            label: 'Commentaire'
            labels: 'Commentaires'
            disabled_actions: ['delete']
            list:
                dql_filter: 'entity.corbeille = false'
                sort: 'page.titre'
                actions:
                    - { name: 'corbeille', label: '', title: 'Mettre à la corbeille', icon: 'trash' }
                fields:
                    - { property: 'page.titre', label: 'Page', sortable: true }
                    - { property: 'auteur', label: 'Auteur', sortable: true }
                    - date
                    - contenu
                    - { property: 'valide', label: 'Validé', sortable: true }
            search:
                sort: 'page.titre'
                fields:
                    - page.titre
                    - auteur.nom
            show:
                fields:
                    - { property: 'page.titre', label: 'Page', sortable: true }
                    - { property: 'auteur.nom', label: 'Auteur', sortable: true }
                    - date
                    - contenu
                    - { property: 'valide', label: 'Validé', sortable: true }
            form:
                actions:
                    - { name: 'corbeille', label: 'Mettre à la corbeille', title: 'Mettre à la corbeille', icon: 'trash' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { property: 'page', label: 'Page', type: 'entity', type_options: { class: 'App\Entity\Page' } }
                    - { property: 'auteur', label: 'Auteur', type: 'text' }
                    - email
                    - site
                    - date
                    - { property: 'contenu', type: 'text' }
            edit:
                fields:
                    - { property: 'valide', label: 'Validé' }
                    - { property: 'corbeille', label: 'Activé' }

        Commentaire_Corbeille:
            class: App\Entity\Commentaire
            label: 'Commentaire à la corbeille'
            labels: 'Commentaires à la corbeille'
            disabled_actions: ['edit']
            list:
                  dql_filter: 'entity.corbeille = true'
                  sort: 'page.titre'
                  actions:
                      - { name: 'corbeille', label: '', title: 'Restaurer', icon: 'recycle' }
                  fields:
                      - { property: 'page.titre', label: 'Page', sortable: true }
                      - { property: 'auteur.nom', label: 'Auteur', sortable: true }
                      - date
                      - contenu