easy_admin:
    entities:
        TypeCategorie:
            class: App\Entity\TypeCategorie
            controller: App\Controller\Back\AdminController
            label: 'Type de catégories'
            labels: 'Types de catégories'
            list:
                actions:
                    - { name: 'voir', label: '', title: 'Voir', icon: 'eye' }
                fields:
                    - nom
                    - { property: 'description', type: 'raw' }
                    - { property: 'seo.url', label: 'Url', type: 'text'}
            search:
                fields:
                    - nom
                    - description
            show:
                fields:
                    - nom
                    - description
                    - seo.url
            form:
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { type: 'tab', label: 'Type de catégorie' }
                    - nom
                    - langue
                    - description
                    - { type: 'tab', label: 'Référencement' }
                    - { property: 'SEO', type: 'App\Form\Type\SEOTypeCategorieType', type_options: { by_reference: true, label: false } }
            edit:
                actions:
                    - { name: 'voir', label: 'Voir', title: 'Voir', icon: 'eye' }
                title: nom
