easy_admin:
    entities:
        Utilisateur:
            class: App\Entity\Utilisateur
            controller: App\Controller\Back\Admin\UtilisateurController
            label: 'Utilisateur'
            labels: 'Utilisateurs'
            labelDeterminant: 'un utilisateur'
            list:
                fields:
                    - { property: 'imageProfil', label: 'Image de profil', type: 'image' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: 'Rôles' }
            search:
                fields:
                    - username
                    - email
            show:
                fields:
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: 'Rôles' }
            form:
                actions:
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
            new:
                fields:
                    - { type: 'tab', label: 'Paramètres du compte' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'E-mail' }
                    - { type: 'group', label: 'Mot de passe', icon: 'key' }
                    - { property: 'plainPassword', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', first_options: { label: 'Mot de passe' }, second_options: { label: 'Répéter le mot de passe' } } }
                    - { type: 'group', label: 'Image de profil', icon: 'camera' }
                    - { property: 'imageProfil', type: 'text', label: 'Image de profil' }
                    - { type: 'group', label: 'Statut', icon: 'user-cog' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'roles', label: 'Rôles', type: 'App\Form\Type\RoleType' }
            edit:
                title: username
                actions:
                    - { name: 'delete', label: 'Supprimer', title: 'Supprimer', icon: 'trash', css_class: '' }
                    - { name: 'list', label: 'Retour', title: 'Retour', icon: 'arrow-left', css_class: '' }
                fields:
                    - { type: 'tab', label: 'Paramètres du compte' }
                    - { property: 'username', label: 'Identifiant' }
                    - { property: 'email', label: 'E-mail' }
                    - { type: 'group', label: 'Mot de passe', icon: 'key', css_class: 'mdp', help: "Pour changer de mot de passer, utilisez <a id=\"modifMDP\" href=\"/profile/change-password\">ce formulaire</a>" }
                    - { type: 'group', label: 'Image de profil', icon: 'camera' }
                    - { property: 'imageProfil', type: 'text', label: 'Image de profil' }
                    - { type: 'group', label: 'Statut', icon: 'user-cog' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'roles', label: 'Rôles', type: 'App\Form\Type\RoleType' }
                    - { type: 'tab', label: "Personnalisation de l'interface" }
                    - { property: 'langue', label: "Langue de l'interface" }
                    - { property: 'couleurBO', type: 'choice', label: "Thème de l'interface d'administration", type_options: { choices: { gris: 'gris', bleu: 'bleu' } } }
                    - { property: 'blocsTableauDeBord', type: 'choice', label: 'Informations présentées sur le tableau de bord', type_options: { multiple: true, expanded: true, choices: { 'Nouvelles de version': logVersion, 'Nombre de pages': nombreDePages, 'Derniers commentaires': derniersCommentaires, 'Dernières pages': dernieresPages, 'Liste des comptes': derniersInscrits, 'Aperçu du référencement': referencement } } }